Clarify unstable build simulation comments in Jenkinsfile
Updated comments in Jenkinsfile to clarify unstable build simulation.

diff --git a/Jenkinsfile3.txt b/Jenkinsfile3.txt
--- a/Jenkinsfile3.txt
+++ b/Jenkinsfile3.txt
@@ -3,11 +3,11 @@ pipeline {
     stages {
         stage('Test') {
             steps {
-                // To simulate unstable build for fail tests, uncomment below 2 lines and comment SUCCESS message.
-                     catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
-                     echo "Tests failed, marking build unstable"
-                     sh 'exit 1' }         
-                 // echo 'SUCCESS'
+                // To simulate unstable build for fail tests, uncomment below 3 lines and comment SUCCESS message.
+                   //  catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
+                   //  echo "Tests failed, marking build unstable"
+                   //  sh 'exit 1' }         
+                  echo 'SUCCESS'
             }
         }
     }
