Update Jenkinsfile3.txt

diff --git a/Jenkinsfile3.txt b/Jenkinsfile3.txt
--- a/Jenkinsfile3.txt
+++ b/Jenkinsfile3.txt
@@ -4,8 +4,8 @@ pipeline {
         stage('Test') {
             steps {
                 // To simulate unstable build for fail tests, uncomment below 2 lines
-                    // catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
-                    // echo 'Fail!'; sh 'exit 1' }         
+                     catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
+                     echo 'Fail!'; sh 'exit 1' }         
                  echo 'SUCCESS'
             }
         }
