Update echo messages for clarity in Jenkinsfile

diff --git a/Jenkinsfile3.txt b/Jenkinsfile3.txt
--- a/Jenkinsfile3.txt
+++ b/Jenkinsfile3.txt
@@ -3,27 +3,27 @@ pipeline {
     stages {
         stage('Test') {
             steps {
-                echo 'Fail!'; exit 1
+                echo 'Fail!'; 'exit 1'
                 echo 'SUCCESS'
             }
         }
     }
     post {
         always {
-            echo 'This will always run'
+            echo 'always : This will always run'
         }
         success {
-            echo 'This will run only if successful'
+            echo 'success : This will run only if successful'
         }
         failure {
-            echo 'This will run only if failed'
+            echo 'failure : This will run only if failed'
         }
         unstable {
-            echo 'This will run only if the run was marked as unstable'
+            echo 'unstable : This will run only if the run was marked as unstable'
         }
         changed {
-            echo 'This will run only if the state of the Pipeline has changed'
-            echo 'For example, if the Pipeline was previously failing but is now successful'
+            echo 'changed : This will run only if the state of the Pipeline has changed from success to fail and vice-versa'
+           
         }
     }
 }
