Update Jenkinsfile3.txt

diff --git a/Jenkinsfile3.txt b/Jenkinsfile3.txt
--- a/Jenkinsfile3.txt
+++ b/Jenkinsfile3.txt
@@ -3,7 +3,7 @@ pipeline {
     stages {
         stage('Test') {
             steps {
-                echo 'Fail!'; sh 'exit 1'
+               // echo 'Fail!'; sh 'exit 1'
                 echo 'SUCCESS'
             }
         }
